version: '2.1'
services:
  app:
    build:
      context: .
    command: ['run', 'test:integration']
    environment:
      - MYSQL_SCHEMA=integration_test_sample
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    entrypoint: npm
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_SCHEMA}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3305:3306'
    networks:
      - net
networks:
  net:
    driver: bridge
